baseurl = "https://vranix.com"
languageCode = "en-us"
title = "vranix"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsCodeFences = true
pygmentsUseClasses = true

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    style = "solarized-dark"
    tabWidth = 4

[Params]
  #subtitle = "Personal website of Shaw Vrana"
  logo = "img/modified.jpg"
  favicon = "img/favicon.png"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = false

[Author]
  name = "shaw"
  email = "shaw@vranix.com"
  github = "svrana"
  twitter = "shawvrana"
  linkedin = "shawvrana"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about"
    weight = 2

[[menu.main]]
    name = "Resume"
    url = "/resume"
    weight = 3

#[[menu.main]]
#    name = "Tags"
#    url = "/tags"
#    weight = 3
