baseURL = 'https://vranix.com/'
languageCode = 'en-us'
defaultConentLanage = "en"
title = 'vranix'
theme = 'KeepIt'

paginate = 12
enableRobotsTXT = true

[Permalinks]
  posts = "/:year/:filename/"

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 4
    Email = "shaw@vranix.com"
  [[menu.main]]
    name = "Resume"
    url = "/resume"
    weight = 4

[params.social]
    GitHub = "svrana"
    Email = "shaw@vranix.com"
    Linkedin = "shawvrana"
    keybase = "svrana"

[params]
	author = "svrana"
	avatar = "/fancypants.jpg"
  #subtitle = "127.0.0.1"
  description = "Shaw Vrana's personal website"
  socialShare = true

[params.share]
  Twitter = true
  Linkedin = true
  Reddit = true
  HackerNews = true
  Facebook = true

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    noHl = true
    style = 'solarized-dark'
    tabWidth = 4
    pygmentsUseClasses = true
    pygmentsCodeFences = true

copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."
